More features
EdmundYuen/lyre-bot pull request #7
Opened 2021-06-11 10:52 UTC by planktonfun

More features

2021-06-12 03:10 UTC, EdmundYuen requested changes

2021-06-12 03:34 UTC, planktonfun commented on README.md
> +  - e.g. `[ADG] [SGJ] [ADH] [MDG]`
I'll add a support for both

2021-06-12 08:11 UTC, planktonfun commented on bot/exts/converter.py
> +    bpm = 0
Updated static methods thing

2021-06-18 16:50 UTC, planktonfun commented
scrap

2021-06-18 16:50 UTC, closed without merging